### PR TITLE
feat: added tattoos and the option to wear/undress clothes.

### PR DESCRIPTION
**Pull request by franfdezmorales**

### CODE REVIEW

**Comment by V3SC** [comment]
if possible can you add the face + hair option for ped characters ?

**Comment by franfdezmorales** [comment]
Hi, could you explain more about this? I dont know what you mean with face + hair option. Ty!

**Comment by V3SC** [comment]
> Hi, could you explain more about this? I dont know what you mean with face + hair option. Ty!

We can't change the hair + face of ped characters. Hair and face customization as with normal characters.

**Review by pedr0fontoura — APPROVED** [review]
Great job, thanks for your efforts. I'll generate a new release with this feature soon.

**Pull request merged**
