### PR TITLE
feature: "es-ES" language

### PR DESCRIPTION
**Pull request by Enz0Z**

### CODE REVIEW

**Comment by franfdezmorales** [comment]
Hi @Enz0Z, with the latest update, you need to update the json, i leave here the data you need to add. Ty in advance!

```json
"tattoos": {
    "title": "Tatuajes",
    "items": {
      "ZONE_TORSO": "Torso",
      "ZONE_HEAD": "Cabeza",
      "ZONE_LEFT_ARM": "Brazo izquierdo",
      "ZONE_RIGHT_ARM": "Brazo derecho",
      "ZONE_LEFT_LEG": "Pierna izquierda",
      "ZONE_RIGHT_LEG": "Pierna derecha"
    },
    "apply": "Aplicar", 
    "delete": "Borrar"
  }
```

**Comment by Enz0Z** [comment]
Hey! There you go!

**Comment by franfdezmorales** [comment]
Hey @Enz0Z, sorry for this, but could you update again with this: 
```json
"headOverlays": {
    "title": "Appearance",
    "hair": {
      "title": "Hair",
      "style": "Style",
      "color": "Color",
      "highlight": "Highlight"
      "highlight": "Highlight", 
      "fade": "Fade"  // This need to be added
    },
    "opacity": "Opacity",
    "style": "Style",
    "color": "Color",
    "blemishes": "Blemishes",
    "beard": "Beard",
    "eyebrows": "Eyebrows",
    "ageing": "Ageing",
    "makeUp": "Make up",
    "blush": "Bblush",
    "complexion": "Complexion",
    "sunDamage": "Sun damage",
    "lipstick": "Lipstick",
    "moleAndFreckles": "Mole and Freckles",
    "chestHair": "Chest hair",
    "bodyBlemishes": "Body blemishes",
    "eyeColor": "Eye color"
  },
```

**Comment by Enz0Z** [comment]
That was what you were looking for?

**Comment by franfdezmorales** [comment]
Thats nice, really ty for ur work!

**Pull request merged**
